# Generated by Django 4.0.1 on 2022-01-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
